"""
Agent Prompts - System prompts and templates for each agent
"""

from app.agents.prompts.supervisor_prompts import (
    SUPERVISOR_SYSTEM_PROMPT,
    INTENT_CLASSIFICATION_PROMPT,
    RESPONSE_FORMAT_TEMPLATE
)
from app.agents.prompts.sql_prompts import (
    SQL_AGENT_SYSTEM_PROMPT,
    SQL_GENERATION_PROMPT,
    SQL_VALIDATION_PROMPT,
    SQL_FIX_PROMPT
)
from app.agents.prompts.dashboard_prompts import (
    DASHBOARD_AGENT_SYSTEM_PROMPT,
    DATA_ANALYSIS_PROMPT,
    VISUALIZATION_SELECTION_PROMPT
)

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "INTENT_CLASSIFICATION_PROMPT",
    "RESPONSE_FORMAT_TEMPLATE",
    "SQL_AGENT_SYSTEM_PROMPT",
    "SQL_GENERATION_PROMPT",
    "SQL_VALIDATION_PROMPT",
    "SQL_FIX_PROMPT",
    "DASHBOARD_AGENT_SYSTEM_PROMPT",
    "DATA_ANALYSIS_PROMPT",
    "VISUALIZATION_SELECTION_PROMPT"
]



